# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions 

name: build-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Push docker Image
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: .
          file: Dockerfile
          repoOwner: ${{ secrets.DOCKERHUB_USERNAME }}
          repository:  swarmtower
          tag: latest
